//
// Created by cemsr on 15.12.2023.
//

#ifndef WORK_COMPLIANCE_ANALYSIS_SYSTEM_SOCIALSKILLS_H
#define WORK_COMPLIANCE_ANALYSIS_SYSTEM_SOCIALSKILLS_H


class SocialSkills {

};


#endif //WORK_COMPLIANCE_ANALYSIS_SYSTEM_SOCIALSKILLS_H
