//
// Created by cemsr on 15.12.2023.
//

#ifndef WORK_COMPLIANCE_ANALYSIS_SYSTEM_HOBIES_H
#define WORK_COMPLIANCE_ANALYSIS_SYSTEM_HOBIES_H


class Hobies {

};


#endif //WORK_COMPLIANCE_ANALYSIS_SYSTEM_HOBIES_H
