//
// Created by cemsr on 15.12.2023.
//

#ifndef WORK_COMPLIANCE_ANALYSIS_SYSTEM_COMMUNICATIONINFORMATION_H
#define WORK_COMPLIANCE_ANALYSIS_SYSTEM_COMMUNICATIONINFORMATION_H


class CommunicationInformation {

};


#endif //WORK_COMPLIANCE_ANALYSIS_SYSTEM_COMMUNICATIONINFORMATION_H
