//
// Created by cemsr on 15.12.2023.
//

#ifndef WORK_COMPLIANCE_ANALYSIS_SYSTEM_EDUCATIONINFORMATION_H
#define WORK_COMPLIANCE_ANALYSIS_SYSTEM_EDUCATIONINFORMATION_H


class EducationInformation {

};


#endif //WORK_COMPLIANCE_ANALYSIS_SYSTEM_EDUCATIONINFORMATION_H
