//
// Created by cemsr on 15.12.2023.
//

#ifndef WORK_COMPLIANCE_ANALYSIS_SYSTEM_EXAMSINFORMATIONS_H
#define WORK_COMPLIANCE_ANALYSIS_SYSTEM_EXAMSINFORMATIONS_H


class ExamsInformations {

};


#endif //WORK_COMPLIANCE_ANALYSIS_SYSTEM_EXAMSINFORMATIONS_H
