//
// Created by cemsr on 15.12.2023.
//

#ifndef WORK_COMPLIANCE_ANALYSIS_SYSTEM_EXPERTISEAREAS_H
#define WORK_COMPLIANCE_ANALYSIS_SYSTEM_EXPERTISEAREAS_H


class ExpertiseAreas {

};


#endif //WORK_COMPLIANCE_ANALYSIS_SYSTEM_EXPERTISEAREAS_H
