//
// Created by cemsr on 15.12.2023.
//

#ifndef WORK_COMPLIANCE_ANALYSIS_SYSTEM_LANGUAGESKILLS_H
#define WORK_COMPLIANCE_ANALYSIS_SYSTEM_LANGUAGESKILLS_H


class LanguageSkills {

};


#endif //WORK_COMPLIANCE_ANALYSIS_SYSTEM_LANGUAGESKILLS_H
