//
// Created by cemsr on 15.12.2023.
//

#ifndef WORK_COMPLIANCE_ANALYSIS_SYSTEM_PROJECTS_H
#define WORK_COMPLIANCE_ANALYSIS_SYSTEM_PROJECTS_H


class Projects {

};


#endif //WORK_COMPLIANCE_ANALYSIS_SYSTEM_PROJECTS_H
