//
// Created by cemsr on 15.12.2023.
//

#ifndef WORK_COMPLIANCE_ANALYSIS_SYSTEM_SERTIFICATES_H
#define WORK_COMPLIANCE_ANALYSIS_SYSTEM_SERTIFICATES_H


class Sertificates {

};


#endif //WORK_COMPLIANCE_ANALYSIS_SYSTEM_SERTIFICATES_H
