//
// Created by cemsr on 15.12.2023.
//

#ifndef WORK_COMPLIANCE_ANALYSIS_SYSTEM_SPECIALEXCEPTIONS_H
#define WORK_COMPLIANCE_ANALYSIS_SYSTEM_SPECIALEXCEPTIONS_H


class SpecialExceptions {

};


#endif //WORK_COMPLIANCE_ANALYSIS_SYSTEM_SPECIALEXCEPTIONS_H
