//
// Created by cemsr on 15.12.2023.
//

#ifndef WORK_COMPLIANCE_ANALYSIS_SYSTEM_WORKCONDITIONS_H
#define WORK_COMPLIANCE_ANALYSIS_SYSTEM_WORKCONDITIONS_H


class WorkConditions {

};


#endif //WORK_COMPLIANCE_ANALYSIS_SYSTEM_WORKCONDITIONS_H
