//
// Created by cemsr on 15.12.2023.
//

#ifndef WORK_COMPLIANCE_ANALYSIS_SYSTEM_WORKEXPERIENCES_H
#define WORK_COMPLIANCE_ANALYSIS_SYSTEM_WORKEXPERIENCES_H


class WorkExperiences {

};


#endif //WORK_COMPLIANCE_ANALYSIS_SYSTEM_WORKEXPERIENCES_H
