//
// Created by cemsr on 15.12.2023.
//

#ifndef WORK_COMPLIANCE_ANALYSIS_SYSTEM_CERTIFICATES_H
#define WORK_COMPLIANCE_ANALYSIS_SYSTEM_CERTIFICATES_H


class Certificates {

};


#endif //WORK_COMPLIANCE_ANALYSIS_SYSTEM_CERTIFICATES_H
