//
// Created by cemsr on 15.12.2023.
//

#ifndef WORK_COMPLIANCE_ANALYSIS_SYSTEM_PERSONALDOCUMENTS_H
#define WORK_COMPLIANCE_ANALYSIS_SYSTEM_PERSONALDOCUMENTS_H


class PersonalDocuments {

};


#endif //WORK_COMPLIANCE_ANALYSIS_SYSTEM_PERSONALDOCUMENTS_H
